### ISSUE TITLE
error when trying to start the app

### ISSUE THREAD

**Issue by BiaSan** [dayvsonlima/catuaba#5]
$ go run application.go
go: downloading github.com/gin-gonic/gin v1.6.3
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/go-playground/validator/v10 v10.3.0
go: downloading github.com/ugorji/go v1.1.7
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/go-playground/universal-translator v0.17.0
go: downloading github.com/leodido/go-urn v1.2.0
go: downloading github.com/go-playground/locales v0.13.0
go: downloading google.golang.org/protobuf v1.24.0
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%

**Comment by rafaelrsantosti** [comment]
Hi @BiaSan What's your OS ? On linux like debian you can install gcc with `$ sudo apt install build-essential` command and on the Windows you need install the https://jmeubank.github.io/tdm-gcc/
